### ISSUE TITLE
Don't depend on the entire Fabric API all at once

### ISSUE THREAD

**Issue by LoganDark** [samolego/IceJar#9]
IceJar depends on a very minimal subset of Fabric API, so it's not fair to declare a dependency on the entire `fabric` mod. AFAIK these are all of the imports IceJar uses from Fabric API (found via [GitHub search](https://github.com/samolego/IceJar/search?q=fabric.api)):

```java
import net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback;
import net.fabricmc.fabric.api.entity.event.v1.ServerPlayerEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.player.AttackBlockCallback;
import net.fabricmc.fabric.api.event.player.AttackEntityCallback;
import net.fabricmc.fabric.api.event.player.UseBlockCallback;
import net.fabricmc.fabric.api.event.player.UseItemCallback;
```

so:

- fabric-command-api-v1
- fabric-entity-events-v1
- fabric-lifecycle-events-v1
- fabric-events-interaction-v0

Fabric API itself has like 40 other modules, so it would be nice not to force their inclusion.

This is likely something to be fixed on release rather than in development, but it's still worth tracking as an issue imho.

**Comment by samolego** [comment]
That's totally doable, but I can't see how an end user would benefit from that :P.

I'll keep it in mind though. IRL stuff is getting in the way atm :P.

**Comment by LoganDark** [comment]
> I can't see how an end user would benefit from that :P

Server admins will - for example, I'd have no need, as a vanilla-like server, to sync registries with or announce custom networking packets to Fabric clients, if there are no mods installed that would utilize that functionality. It's more a peace of mind thing than an actual practical performance degradation, even with 40+ API modules.

**Comment by LoganDark** [comment]
I've made a suggestion on the template repository that goes into more detail on this: https://github.com/FabricMC/fabric-example-mod/issues/175

**Comment by samolego** [comment]
I've tried getting this to work, but it crashes when starting to load server *on modules that shouldn't even be loaded* (e.g. `registry-sync`) :thinking:

**Comment by samolego** [comment]
It seems that it was due to config2brigadier lib; however, I'll wait to see how the mentioned issue plays out

**Comment by LoganDark** [comment]
ah, another mod depending on the entirety of `fabric` would do it, yep. If you do this in all your mods then it might take a while to transition.

**Comment by LoganDark** [comment]
Thanks!
